debug: false
spring:
  security:
    user:
      name: money-user
      password: money-pass
  datasource:
    url: jdbc:postgresql://localhost:5432/money
    username: money
    password: money
  jpa:
    properties:
      hibernate:
        generate_statistics: false
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        ddl-auto: verify
        jdbc.lob.non_contextual_creation: true
  zipkin:
    service:
      name: @project.name@
logging:
  org.hibernate.engine.internal.StatisticalLoggingSessionListener: INFO
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: never
  metrics:
    tags:
      application: @project.name@
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    export:
      influx:
        org: @influx.org@
        enabled: true
        bucket: @influx.bucket@
        auto-create-db: false
        token: @influx.token@
  info:
    git:
      mode: full
info:
  app:
    name: @project.artifactId@-@version@
    description: @project.description@
  build:
    groupId: @project.groupId@
    artifact: @project.artifactId@
    name: @project.name@
    version: @version@
